# templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "productcm.fullname" . }}
  labels:
    {{- include "productcm.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "productcm.fullname" . }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
